djangoDovolena_projekt/urls.py
"""
URL configuration for djangoDovolena_projekt project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dovolena.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dovolena/urls.py
from django.urls import path
from . import views


from django.views.generic import TemplateView

app_name = 'dovolena'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('dovolena/', views.DovolenaListView.as_view(), name='dovolena_list'),
    path('dovolena/<int:pk>/', views.DovolenaDetailView.as_view(), name='dovolena_detail'),
    path('flight/', views.FlightListView.as_view(), name='flight_list'),
    path('flight/<int:pk>/', views.FlightDetailView.as_view(), name='flight_detail'),
    path('recenze/', views.RecenzeListView.as_view(), name='recenze_list'),
    path('recenze/<int:pk>/', views.RecenzeDetailView.as_view(), name='recenze_detail'),
    path('rezervace', views.RezervaceListView.as_view(), name='rezervace_list'),
    path('rezervace/<int:pk>/', views.RezervaceDetailView.as_view(), name='rezervace_detail'),
    path('ucastnik/', views.UcastnikListView.as_view(), name='ucastnik_list'),
    path('ucastnik/<int:pk>/', views.UcastnikDetailView.as_view(), name='ucastnik_detail'),
]

dovolena/models.py
from django.db import models
from django.core.exceptions import ValidationError


class Ucastnik(models.Model):
    jmeno = models.CharField(
        max_length=80,
        verbose_name='Jméno účastníka',
        help_text='Zadejte jméno účastníka',
        error_messages={'blank': 'Jméno účastníka musí být vyplněno'}
    )
    prijmeni = models.CharField(
        max_length=50,
        verbose_name='Příjmení účastníka',
        help_text='Zadejte příjmení účastníka',
        error_messages={'blank': 'Příjmení účastníka musí být vyplněno'}
    )
    email = models.EmailField(
        max_length=50,
        verbose_name='E-mail účastníka',
        help_text='Zadejte E-mail účastníka',
        error_messages={'blank': 'E-mail účastníka musí být vyplněný'}
    )
    telefon = models.CharField(
        max_length=15,
        verbose_name='Telefon účastníka',
        help_text='Zadejte telefonní číslo',
        error_messages={'blank': 'Telefon účastníka musí být vyplněný'}
    )
    datum_narozeni = models.DateField(
        verbose_name='Datum narození účastníka',
        help_text='Zadejte datum narození',
        error_messages={'blank': 'Datum narození musí být vyplněný'}
    )

    class Meta:
        ordering = ['prijmeni', 'jmeno']
        verbose_name = 'Účastník'
        verbose_name_plural = 'Účastníci'

    def __str__(self):
        return f'{self.prijmeni} {self.jmeno} {self.email} {self.telefon} {self.datum_narozeni}'


class Dovolena(models.Model):
    destinace = models.CharField(
        max_length=20,
        blank=True,
        null=True,
        verbose_name='Destinace',
        help_text='Zadejte destinace'
    )
    zacatek_terminu = models.DateField(
        verbose_name='Začátek dovolené',
        help_text='Zadejte začátek vaší dovolené',
        error_messages={'blank': 'Začátek termínu musí být vyplněný'}
    )
    konec_terminu = models.DateField(
        verbose_name='Konec dovolené',
        help_text='Zadejte konec vaší dovolené',
        error_messages={'blank': 'Konec termínu musí být vyplněný'}
    )

    class Meta:
        verbose_name = "Dovolená"
        verbose_name_plural = "Dovolené"
        ordering = ['destinace', 'zacatek_terminu', 'konec_terminu']

    def __str__(self):
        return f"{self.destinace} {self.zacatek_terminu} {self.konec_terminu}"

class Flight(models.Model):
    AIRPORT_CHOICES = (
        ('BRNO', 'Brno'),
        ('PRAHA', 'Praha'),
        ('OSTRAVA', 'Ostrava'),
    )

    misto_odletu = models.CharField(
        max_length=7,
        choices=AIRPORT_CHOICES,
        verbose_name='Místo odletu',
        help_text='Zadej místo odletu',
        error_messages={'blank': 'Místo odletu musí být zadáno'}
    )

    class Meta:
        verbose_name = "Let"
        verbose_name_plural = "Lety"

    def __str__(self):
        return f"{self.get_misto_odletu_display()} ({self.misto_odletu})"


class Rezervace(models.Model):
    pocet_ucastniku = models.IntegerField(
        verbose_name='Počet účastníků',
        help_text='Zadejte počet účastníků',
        error_messages={'blank': 'Počet účastníků musí být vyplněný'}
    )
    celkem_cena = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        verbose_name='Celková cena',
        help_text='Zadejte celkovou cenu',
        error_messages={'blank': 'Celková cena musí být vyplněná'}
    )

    class Meta:
        verbose_name = "Rezervace"
        verbose_name_plural = "Rezervace"
        ordering = ['id']

    def __str__(self):
        return f"Rezervace {self.id} - Počet účastníků: {self.pocet_ucastniku}, Cena: {self.celkem_cena}"


def validate_rating(value):
    if value < 1 or value > 5:
        raise ValidationError(
            'Hodnocení musí být mezi 1 a 5.',
            params={'value': value},
        )


class Recenze(models.Model):
    rating = models.IntegerField(
        verbose_name="Rating",
        help_text="Hodnocení musí být mezi 1 a 5",
        validators=[validate_rating]
    )
    review = models.TextField(
        verbose_name="Recenze",
        blank=True,
        null=True,
        help_text="Přidejte recenzi"
    )

    class Meta:
        verbose_name = "Recenze"
        verbose_name_plural = "Recenze"
        ordering = ['id']

    def __str__(self):
        return f"Recenze {self.rating}"

dovolena/views.py
from django.views.generic import DetailView, ListView
from .models import Ucastnik, Dovolena, Flight, Rezervace, Recenze


class UcastnikListView(ListView):
    model = Ucastnik
    template_name = 'ucastnik/ucastnik_detail.html'
    context_object_name = 'ucastnici'


class UcastnikDetailView(DetailView):
    model = Ucastnik
    template_name = 'ucastnik/ucastnik_detail.html'
    context_object_name = 'ucastnik'


class DovolenaListView(ListView):
    model = Dovolena
    template_name = 'dovolena/dovolena_list.html'
    context_object_name = 'dovolene'


class DovolenaDetailView(DetailView):
    model = Dovolena
    template_name = 'dovolena/dovolena_detail.html'
    context_object_name = 'dovolena'


class FlightListView(ListView):
    model = Flight
    template_name = 'flight/flight_list.html'
    context_object_name = 'flights'


class FlightDetailView(DetailView):
    model = Flight
    template_name = 'flight/flight_detail.html'
    context_object_name = 'flight'


class RezervaceListView(ListView):
    model = Rezervace
    template_name = 'rezervace/rezervace_list.html'
    context_object_name = 'rezervace'


class RezervaceDetailView(DetailView):
    model = Rezervace
    template_name = 'rezervace/rezervace_detail.html'
    context_object_name = 'rezervace'


class RecenzeListView(ListView):
    model = Recenze
    template_name = 'recenze/recenze_list.html'
    context_object_name = 'recenze'


class RecenzeDetailView(DetailView):
    model = Recenze
    template_name = 'recenze/recenze_detail.html'
    context_object_name = 'recenze'

dovolena/templates/base.html
<!DOCTYPE html>
<html lang="cs">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Sklad{% endblock %}</title>
    <!-- Bootstrap CSS -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

</head>
<body>
    <!-- Záhlaví -->
     {% include 'page/header.html' %}

    <!-- Navigace -->
    {% include 'page/navbar.html' %}
    <!-- Obsah stránky -->
    <main class="container">
    {% block content %}{% endblock %}
    </main>
    <!-- Zápatí -->
     {% include 'page/footer.html' %}
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'bootstrap/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
    {% block script %}{% endblock %}
</body>
</html>

dovolena/templates/dovolena/dovolena_detail.html
 {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Detail dovolené</h1>
        <div>
            <p><strong>Destinace:</strong> {{ dovolena.destinace }}</p>
            <p><strong>Začátek termínu:</strong> {{ dovolena.zacatek_terminu }}</p>
            <p><strong>Konec termínu:</strong>{{ dovolena.konec_terminu }}</p>
        </div>
    </div>
{% endblock %}

dovolena/templates/dovolena/dovolena_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1 class="mb-4">Seznam dovolených</h1>
        <div class="list-group">
            {% for dovolena in dovolene %}
            <div class="item">
                <div class="info">
                    <h5> <a href="{% url 'dovolena:dovolena_detail' dovolena.pk %}" > {{ dovolena.destinace }} </a></h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dovolena/templates/flight/flight_detail.html
 {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Detail místa odletu</h1>
        <div>
            <p><strong>Místo odletu:</strong> {{ flight.misto_odletu }}</p>
        </div>
    </div>
{% endblock %}

dovolena/templates/flight/flight_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1 class="mb-4">Seznam míst odletu</h1>
        <div class="list-group">
            {% for flight in flights %}
            <div class="item">
                <div class="info">
                    <h5> <a href="{% url 'dovolena:flight_detail' flight.pk %}">{{ flight.misto_odletu }}</a></h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dovolena/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-12 text-center bg-info mt-3 mb-3 box-rounded">
        <h2 class="text-white p-3">Vítejte na Naší Stránce</h2>
    </div>
    <div class="text-center">
        <p>
            Vítejte na naší stránce věnované dovoleným! Dovolená je klíčovým prvkem v našich životech, ať už jde o krátké výlety, středně dlouhé pobyty nebo velké dobrodružné cesty. Efektivní plánování dovolené může výrazně ovlivnit vaše zážitky, pohodu a spokojenost.
        </p>
        <p>
            Naše stránka vám přináší ucelené informace o destinacích, strategiích a tipech pro plánování dovolené, nejnovějších trendech v cestování, moderních technologiích využívaných pro rezervace a mnoho dalšího. Chceme vám poskytnout užitečné tipy a návody pro optimalizaci vašeho cestování a zlepšení vašich zážitků.
        </p>
        <p>
            Nezáleží na tom, jestli jste začínající cestovatel hledající základní informace o plánování dovolené, nebo zkušený cestovatel, který hledá nové inspirace a strategie, na naší stránce určitě najdete cenné informace a inspiraci pro vaše cesty.
        </p>
        <p>
            Přejeme vám příjemné procházení naší stránky a mnoho úspěchů ve vašich cestovatelských dobrodružstvích!
        </p>
    </div>
</div>
{% endblock %}

dovolena/templates/page/footer.html
{% load static %}
<footer class="container p-3 bg-light border">
    <p class="text-center text-dark">&copy; 2024 David Beneš</p>
    <p class="text-center"><img src="{% static 'img/skola-logo.png' %}" alt="Logo školy"></p>
</footer>

dovolena/templates/page/header.html
{% load static %}

<header class="bg-primary p-3 text-center">
    <h1 class="display-3 text-white">Dovolena</h1>
</header>

dovolena/templates/page/navbar.html
{% load static %}

<nav class="navbar navbar-expand-sm navbar-dark bg-primary">
    <a class="navbar-brand navbar-marg text-light" href="../">Úvodní stránka <span class="sr-only">(current)</span></a>
    <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId"
            aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
    <div class="collapse navbar-collapse" id="collapsibleNavId">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">

            </li>
            <li class="nav-item ">
                    <a class="navbar-brand navbar-marg text-light" href="{% url 'dovolena:dovolena_list' %}">Dovolená</a>
                    <a class="navbar-brand navbar-marg text-light" href="{% url 'dovolena:flight_list' %}">List letů</a>
                    <a class="navbar-brand navbar-marg text-light" href="{% url 'dovolena:recenze_list' %}">Recenze</a>
                    <a class="navbar-brand navbar-marg text-light" href="{% url 'dovolena:rezervace_list' %}">Rezervace</a>
                    <a class="navbar-brand navbar-marg text-light" href="{% url 'dovolena:ucastnik_list' %}">Ucastnik</a>
            </li>
        </ul>
    </div>
    
</nav>

dovolena/templates/recenze/recenze_detail.html
 {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Detail recenzí</h1>
        <div>
            <p><strong>Hodnocení:</strong> {{ recenze.rating}}</p>
            <p><strong>Recenze:</strong> {{ recenze.review }}</p>
        </div>
    </div>
{% endblock %}

dovolena/templates/recenze/recenze_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1 class="mb-4">Seznam recenzí</h1>
        <div class="list-group">
            {% for recenze in recenze %}
            <div class="item">
                <div class="info">
                    <h5> <a href="{% url 'dovolena:recenze_detail' recenze.pk %}" > {{ recenze.rating }} </a></h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dovolena/templates/rezervace/rezervace_detail.html
 {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Detail rezervací</h1>
        <div>
            <p><strong>Počet účastníků:</strong> {{ rezervace.pocet_ucastniku}}</p>
            <p><strong>Cena celkem:</strong> {{ rezervace.celkem_cena }}</p>
        </div>
    </div>
{% endblock %}

dovolena/templates/rezervace/rezervace_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1 class="mb-4">Seznam rezervací</h1>
        <div class="list-group">
            {% for rezervace in rezervace %}
            <div class="item">
                <div class="info">
                    <h5> <a href="{% url 'dovolena:rezervace_detail' rezervace.pk %}" > {{ rezervace.pocet_ucastniku }} </a></h5>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

dovolena/templates/ucastnik/ucastnik_detail.html
 {% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
        <h1 class="mb-4">Detail účastníků</h1>
        <div>
            <p><strong>Jméno:</strong> {{ ucastnik.jmeno}}</p>
            <p><strong>Příjmení:</strong> {{ ucastnik.prijmeni }}</p>
            <p><strong>Datum narození:</strong> {{ ucastnik.datum_narozeni}}</p>
            <p><strong>Email:</strong> {{ ucastnik.email }}</p>
            <p><strong>Telefon:</strong> {{ ucastnik.telefon }}</p>
        </div>
    </div>
{% endblock %}

dovolena/templates/ucastnik/ucastnik_list.html
{% extends 'base.html' %}

{% block content %}

    <div class="container mt-5">
        <h1 class="mb-4">Seznam účastníků</h1>
        <div class="list-group">
            {% for ucastnik in ucastnici %}
                <div class="item">
                    <div class="info">
                        <h5><a href="{% url 'dovolena:ucastnik_detail' ucastnik.pk %}"> {{ ucastnik.jmeno }} </a></h5>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}